
var places = [
    //midrandrank
         {rank: "Midrand Rank", from: "Midrand Rank", to: "Alexander",
                  id: 1, sign: require('../images/signs/pointfingerleft.png'), 
                                   price: "R14.00", times: "05:00-17:00",
                                         view: require('../images/khombataxirank.png')},
         {rank: "Midrand Rank", from: "Midrand Rank", to: "KemptonPark",
                 id: 2, sign: require('../images/signs/point1up.png'), 
                                   price: "R15.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')},
         {rank: "Midrand Rank", from: "Midrand Rank", to: "Daveyton",
                 id: 3, sign: require('../images/signs/pointoutfist.png'),
                                   price: "R18.00", times: "08:00-20:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')},
       
    
         {rank: "Midrand Rank", from: "Midrand Rank", to: "Johannesburg CBD",
                  id: 4, sign: require('../images/signs/point2up.png'), price: "R14.00", times: "05:00-17:00",
                                         view: require('../images/taxirank/Khomba-Bree-Image.png')},
         {rank: "Midrand Rank", from: "Midrand Rank", to: "Polokwane",
                 id: 11, sign: require('../images/signs/point5up.png'), price: "R260.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')},
         {rank: "Midrand Rank", from: "Midrand Rank", to: "Bara Hospital",
                 id: 12, sign: require('../images/signs/point5up.png'), price: "R18.00", times: "08:00-20:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')},
    
    
         {rank: "Midrand Rank", from: "Midrand Rank", to: "Germiston",
                  id: 13, sign: require('../images/signs/pointoutfist.png'), price: "R15.50", times: "05:00-17:00",
                                         view: require('../images/taxirank/Khomba-Bree-Image.png')},
         {rank: "Midrand Rank", from: "Midrand Rank", to: "Thembisa Sangweni",
                 id: 14, sign: require('../images/signs/halfwaycutting.png'), price: "R14.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')},
         {rank: "Midrand Rank", from: "Midrand Rank", to: "Thembisa Straight",
                 id: 15, sign: require('../images/signs/halfwaycutting.png'), price: "R12.00", times: "08:00-20:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')},
        
    
         {rank: "Midrand Rank", from: "Midrand Rank", to: "Kalfontein Straight",
                  id: 16, sign: require('../images/signs/halfwaycutting.png'), price: "R12.00", times: "05:00-17:00",
                                         view: require('../images/taxirank/Khomba-Bree-Image.png')},
         {rank: "Midrand Rank", from: "Midrand Rank", to: "Kalfontein Ebony",
                 id: 17, sign: require('../images/signs/halfwaycutting.png'), price: "R12.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')},
         {rank: "Midrand Rank", from: "Midrand Rank", to: "Ivory Park Score",
                 id: 18, sign: require('../images/signs/halfwaycutting.png'), price: "R12.00", times: "08:00-20:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')},
    
    
         {rank: "Midrand Rank", from: "Midrand Rank", to: "Ivory Park Tswela Pele",
                  id: 19, sign: require('../images/signs/halfwaycutting.png'), price: "R12.00", times: "05:00-17:00",
                                         view: require('../images/taxirank/Khomba-Bree-Image.png')},
         {rank: "Midrand Rank", from: "Midrand Rank", to: "Randburg/4-ways/Kyalami",
                 id: 1, sign: require('../images/signs/point5up.png'), price: "R14.50", times: "06:00-19:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')},
         {rank: "Midrand Rank", from: "Midrand Rank", to: "Rabaridge",
                 id: 2, sign: require('../images/signs/point2up.png'), price: "R12.00", times: "08:00-20:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')},
    
    
         {rank: "Midrand Rank", from: "Midrand Rank", to: "Ivory Park 2",
                  id: 3, sign: require('../images/signs/point2up.png'), price: "R12.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Khomba-Bree-Image.png')},
         {rank: "Midrand Rank", from: "Midrand Rank", to: "Ivory Park Em-l-eni",
                 id: 4, sign: require('../images/signs/point2up.png'), price: "R12.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')},
         {rank: "Midrand Rank", from: "Midrand Rank", to: "Ivory Park Ma-b-ye",
                 id: 5, sign: require('../images/signs/point2up.png'), price: "R12.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')},
         {rank: "Midrand Rank", from: "Midrand Rank", to: "Pretoria",
                  id: 6, sign: require('../images/signs/snake.png'), price: "R16.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Khomba-Bree-Image.png')},
         {rank: "Midrand Rank", from: "Midrand Rank", to: "Spruitview",
                 id: 7, sign: require('../images/signs/point5up.png'), price: "R18.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')},
         {rank: "Midrand Rank", from: "Midrand Rank", to: "Waterfall",
                 id: 1, sign: require('../images/signs/point7up.png'), price: "R12.50", times: "06:00-19:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')},
    
    
         {rank: "Midrand Rank", from: "Midrand Rank", to: "Diepsloot",
                  id: 1, sign: require('../images/signs/wave.png'), price: "R16.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Khomba-Bree-Image.png')},
         {rank: "Sandton Rank", from: "Sandton Rank", to: "CBD",
                 id: 1, sign: require('../images/signs/point1up.png'), price: "R12.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')},
         {rank: "Sandton Rank", from: "Sandton Rank", to: "Bara Hospital Soweto",
                 id: 1, sign: require('../images/signs/point1up.png'), price: "R18.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')},
         {rank: "Sandton Rank", from: "Sandton Rank", to: "Yoeville",
                  id: 2, sign: require('../images/signs/point5up.png'), price: "R13.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Khomba-Bree-Image.png')},
         {rank: "Sandton Rank", from: "Sandton Rank", to: "Rabaridge",
                 id: 2, sign: require('../images/signs/point5up.png'), price: "R14.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')},
         {rank: "Sandton Rank", from: "Sandton Rank", to: "Alex / Local",
                 id: 3, sign: require('../images/signs/point1down.png'), price: "R9.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')},
    
    
         {rank: "Sandton Rank", from: "Sandton Rank", to: "Thembisa",
                  id: 4, sign: require('../images/signs/snakeupdown.png'), price: "R15.50", times: "06:00-19:00",
                                         view: require('../images/taxirank/Khomba-Bree-Image.png')},
         {rank: "Sandton Rank", from: "Sandton Rank", to: "Straight Line and Main Line",
                 id: 1, sign: require('../images/signs/snakeupdown.png'), price: "R17.50", times: "06:00-19:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')},
         {rank: "Sandton Rank", from: "Sandton Rank", to: "Phomolong",
                 id: 2, sign: require('../images/signs/snakeupdown.png'), price: "R15.50", times: "06:00-19:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')},
         {rank: "Sandton Rank", from: "Sandton Rank", to: "Vosloo/Spruitview",
                  id: 3, sign: require('../images/signs/point5up.png'), price: "R24.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Khomba-Bree-Image.png')},
         {rank: "Sandton Rank", from: "Sandton Rank", to: "Stop 12",
                 id: 5, sign: require('../images/signs/point6sharp.png'), price: "R14.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')},
         {rank: "Sandton Rank", from: "Sandton Rank", to: "Pretoria",
                 id: 4, sign: require('../images/signs/point5up.png'), price: "R25.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')},
    
    
         {rank: "Sandton Rank", from: "Sandton Rank", to: "Ivory Park 2",
                  id: 6, sign: require('../images/signs/point2up.png'), price: "R14.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Khomba-Bree-Image.png')},
         {rank: "Sandton Rank", from: "Sandton Rank", to: "Ivory Park 3",
                 id: 7, sign: require('../images/signs/point3up.png'), price: "R15.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')},
    
         {rank: "Sandton Rank", from: "Sandton Rank", to: "Ebony Park",
                 id: 1, sign: require('../images/signs/fivefingersconedspider.png'), price: "R14.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')},
         {rank: "Sandton Rank-nb", from: "Sandton Rank-nb", to: "Fourways",
                  id: 1, sign: require('../images/signs/point4up.png'), price: "R14.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Khomba-Bree-Image.png')},
    
         {rank: "Sandton Rank-nb", from: "Sandton Rank-nb", to: "DainFern",
                 id: 2, sign: require('../images/signs/point4up.png'), price: "R14.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')},
         {rank: "Sandton Rank-nb", from: "Sandton Rank-nb", to: "Diepsloot",
                 id: 3, sign: require('../images/signs/snakeupdown.png'), price: "R15.50", times: "06:00-19:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')},
    
    
         {rank: "Rosebank Rank", from: "Rosebank Rank", to: "Alex",
                  id: 1, sign: require('../images/signs/point1forward.png'), price: "R11", times: "06:00-19:00",
                                         view: require('../images/taxirank/Khomba-Bree-Image.png')},
         {rank: "Rosebank Rank", from: "Rosebank Rank", to: "Ivory/Raba Ritch",
                 id: 2, sign: require('../images/signs/point2up.png'), price: "R15.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')},
         {rank: "Rosebank Rank", from: "Rosebank Rank", to: "Thembisa",
                 id: 3, sign: require('../images/signs/atwith2.png'), price: "R16.50", times: "06:00-19:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')},
         {rank: "Rosebank Rank", from: "Rosebank Rank", to: "CBD",
                  id: 4, sign: require('../images/signs/point1up.png'), price: "R10.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Khomba-Bree-Image.png')},
    
         {rank: "Rosebank Rank", from: "Rosebank Rank", to: "Midrand/Allandale",
                 id: 5, sign: require('../images/signs/halfwaycutting.png'), price: "R13.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')},
         {rank: "Bree Rank - Ground", from: "Bree Rank - Ground", to: "Cosmo City",
                 id: 1, sign: require('../images/signs/point5up.png'), price: "R18.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')},
    
    
         {rank: "Bree Rank - Ground", from: "Bree Rank - Ground", to: "Jan Smuts",
                  id: 2, sign: require('../images/signs/point1down.png'), price: "R13.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Khomba-Bree-Image.png')},
         {rank: "Bree Rank - Ground", from: "Bree Rank - Ground", to: "Parkhurst",
                 id: 3, sign: require('../images/signs/point1down.png'), price: "R13.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')},
    
         {rank: "Bree Rank - Ground", from: "Bree Rank - Ground", to: "Fairlands",
                 id: 4, sign: require('../images/signs/point1right.png'), price: "R13.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')},
         {rank: "Bree Rank - Ground", from: "Bree Rank - Ground", to: "Maringa / Randburg",
                  id: 5, sign: require('../images/signs/point1down.png'), price: "R13.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Khomba-Bree-Image.png')},
    
         {rank: "Bree Rank - Ground", from: "Bree Rank - Ground", to: "Honeydew",
                 id: 6, sign: require('../images/signs/point1forward.png'), price: "R16.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')},
         {rank: "Bree Rank - Ground", from: "Bree Rank - Ground", to: "Radiokop/Cresta",
                 id: 7, sign: require('../images/signs/point3up.png'), price: "R16.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')},
    
    
         {rank: "Bree Rank - Ground", from: "Bree Rank - Ground", to: "Boskop",
                  id: 8, sign: require('../images/signs/point1down.png'), price: "R14.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Khomba-Bree-Image.png')},
         {rank: "Bree Rank - Ground", from: "Bree Rank - Ground", to: "Storm Park",
                 id: 9, sign: require('../images/signs/point1down.png'), price: "R14.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')},
    
         {rank: "Bree Rank - Ground", from: "Bree Rank - Ground", to: "Auckland Park",
                 id: 10, sign: require('../images/signs/point1down.png'), price: "R8.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')},
         {rank: "Bree Rank - Ground", from: "Bree Rank - Ground", to: "SpruitView",
                  id: 11, sign: require('../images/signs/point7up.png'), price: "R15.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')},
    
         {rank: "Bree Rank - Ground", from: "Bree Rank - Ground", to: "Julies",
                 id: 12, sign: require('../images/signs/point1ahead.png'), price: "R11.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')},
         {rank: "Bree Rank - Ground", from: "Bree Rank - Ground", to: "East Gate",
                 id: 13, sign: require('../images/signs/point5up.png'), price: "R10.50", times: "06:00-19:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')},
    
    
         {rank: "Bree Rank - Ground", from: "Bree Rank - Ground", to: "Yoeville",
                  id: 14, sign: require('../images/signs/point1down.png'), price: "R10.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Khomba-Bree-Image.png')},
         {rank: "Bree Rank - Ground", from: "Bree Rank - Ground", to: "Fourways/Diepslot",
                 id: 15, sign: require('../images/signs/wave.png'), price: "R19.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')},
    
         {rank: "Bree Rank - Top", from: "Bree Rank - Top", to: "Morafe",
                 id: 1, sign: require('../images/signs/point1up.png'), price: "R12.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')},
         {rank: "Bree Rank - Top", from: "Bree Rank - Top", to: "Naledi",
                  id: 2, sign: require('../images/signs/point1up.png'), price: "R13.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Khomba-Bree-Image.png')},
         {rank: "Bree Rank - Top", from: "Bree Rank - Top", to: "Pimville",
                 id: 3, sign: require('../images/signs/point1up.png'), price: "R11.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')},
         {rank: "Bree Rank - Top", from: "Bree Rank - Top", to: "Shawela",
                 id: 4, sign: require('../images/signs/point1up.png'), price: "R12.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')},
    
         {rank: "Bree Rank - Top", from: "Bree Rank - Top", to: "The Glen",
                  id: 5, sign: require('../images/signs/point1up.png'), price: "R14.00", times: "06:00-19:00",
                                         view: require('../images/taxirank/Khomba-Bree-Image.png')},
         {rank: "Bree Rank - Top", from: "Bree Rank - Top", to: "Zola/Dube/Orlando",
                 id: 6, sign: require('../images/signs/point1up.png'), price: "R13.50", times: "06:00-19:00",
                                         view: require('../images/taxirank/Rosebank-Taxi-Rank.png')}
    
    
        ];
    
    export default places;
    
    
    